add check_error

diff --git a/templates/script/check_kopia.sh.j2 b/templates/script/check_kopia.sh.j2
--- a/templates/script/check_kopia.sh.j2
+++ b/templates/script/check_kopia.sh.j2
@@ -54,5 +54,11 @@ for folder in `$KOPIA_BIN snapshot ls | grep $HOSTNAME |awk '{print $1}' | cut -
       if ! [ $_diff_date -lt $_duree_limite ];then
         _status="KO"
       fi
+# check des snap en error
+    _check_error=$($KOPIA_BIN snapshot ls $folder | grep 'latest-1,' | grep 'error')
+      if ! [ -z "$_check_error" ];then
+        _status="ERROR ON SNAP"
+	#echo "$_check_error"
+      fi
   done
 echo $_status
